# config file for the job execution on cluster 

__default__:
    account: "ClinicalMicrobio"
    cpus-per-task: "{threads}"
    time: "04:00:00"
    mem: 8000
    
    output: "logs/{rule}-%j.out"

    error: "logs/{rule}-%j.err"


